baseURL = "https://koosjuh.github.io"
languageCode = "en-us"
title = "Koos's Tech Blog"
theme = "toha"

[params]
description = "Security, Microsoft, homelab, and tech write-ups"

[params.author]
name = "Koos Janse"
nickname = "Koos"
image = "images/avatar.png"

[params.contactInfo]
email = "koos@koosjanse.com"
github = "Koosjuh"
linkedin = "https://www.linkedin.com/in/koosjanse"
