name: Theme Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-theme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Hugo CLI
        env:
          HUGO_VERSION: 0.156.0
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Update Hugo modules
        run: |
          hugo mod get -u
          hugo mod npm pack
          hugo mod tidy

      - name: Install node modules
        run: npm ci

      - name: Build
        run: |
          hugo --minify
          rm -rf public/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          title: Update theme
